### ISSUE TITLE
自定义getById()查询方法中混入了book表中的字段，很迷惑，求教

### ISSUE THREAD

**Issue by biotech7** [TaleLin/lin-cms-spring-boot#101]
按照https://doc.cms.talelin.com/start/spring-boot/backend-demo.html的介绍，我自定义了一个表goods，然后按照教程创建了对应的数据层，模型层，业务层（包括映射xml文件等已建好）和控制层。

然后用postman工具运行get请求，localhost:5000/v1/goods/1，返回错误："code": 9999,
    "message": "服务器未知错误"
查看后台日志发现：对mysql查询数据时，竟然在mysql运行语句中出现了框架自带的book表的字段，进行多轮排查，找不到根本原因，请求帮助！

![11](https://user-images.githubusercontent.com/49674341/90136538-e7b61180-dda6-11ea-8bd1-b2074421ede7.png)

**Comment by juzi214032** [comment]
`create_time`和`update_time`是通用基础字段，如果不想要这两个字段， 不要继承`BaseModel`即可

**Comment by biotech7** [comment]
感谢，的确是继承了basemodel的原因，但是当我把数据库配置修改成自定义参数后，目标是访问goods这个表，结果出现了访问权限的错误，后台错误信息是这样的:

Cause: java.sql.SQLSyntaxErrorException: Table 'goods.lin_permission' doesn't exist

请问这是一个怎样的权限错误，在哪里修改参数纠正？

**Comment by juzi214032** [comment]
数据库里面没有`lin_permission`这张表，检查一下表是否完整

**Comment by biotech7** [comment]
没有把这张表拷贝进去，现在解决了，非常感谢！

**Comment by juzi214032** [comment]
不客气

**Comment by biotech7** [comment]
我想用其它名字建一个超级管理员(root)的登录账户（比如用admin），在lin_user_identity表中，把admin的user_id设成了1（默认是2），注入对应密码，然后通过postman用admin登录，结果返回服务器内部错误。怎样才能设置成功？

**Comment by juzi214032** [comment]
> 我想用其它名字建一个超级管理员(root)的登录账户（比如用admin），在lin_user_identity表中，把admin的user_id设成了1（默认是2），注入对应密码，然后通过postman用admin登录，结果返回服务器内部错误。怎样才能设置成功？

请重新提一个issue
