### ISSUE TITLE
新建超级管理员账户是否有可能？

### ISSUE THREAD

**Issue by biotech7** [TaleLin/lin-cms-spring-boot#102]
我想用其它名字建一个超级管理员(root)的登录账户（比如用admin），在lin_user_identity表中，把admin的user_id设成了1（默认是2），注入对应密码，然后通过postman用admin登录，结果返回服务器内部错误。怎样才能设置成功？

**Comment by colorful3** [comment]
`lin-cms` 默认只有一个超级管理用用户，适用觉大多数场景。如果想要新增多名超级管理员用户，可能要自己看下源码了，改一些用户相关代码的逻辑。

**Comment by biotech7** [comment]
好的，我试试看看能否改成功
