### ISSUE TITLE
JWT 生成  generateToken只能传入 long 类型的 identity 如果过想传入 String类型 需要重写 JWT，建议提供一下 String 的方法

### ISSUE THREAD

**Issue by yangxin6** [TaleLin/lin-cms-spring-boot#106]
CMS 是一个颇为复杂的应用，它需要的东西太多。我们无法涉及到方方面面，因此关于新特性，我们会以讨论的形式来确定这个特性是否去实现，以什么形式实现。
我们鼓励所有对这个特性感兴趣的人来参与讨论，当然如果你想参与特性的开发那就更好了。

如果你实现了一个 feature，并通过了单元测试，请用`git rebase`合并成一条标准的`feat: description`提交，然后向我们的
项目提 PR，我们会在第一时间审核，并感谢您的参与。

**请问这个特性跟什么问题相关？ 有哪些应用场景？请详细描述。**
请清晰准确的描述问题的内容，以及真实的场景。

**请描述一下你想怎么实现这个特性**
怎么样去实现这个特性？加入核心库？加入工程项目？还是其他方式。
当然你也可以描述它的具体实现.

**讨论**
如果这个特性应用场景非常多，或者非常重要，我们会第一时间去处理。但更多的我们希望更多的人参与讨论，来斟酌它的可行性。

**Comment by colorful3** [comment]
你好，为提供更丰富方便的接口，核心库代码已经修改，重载了此方法，想要使用还要等下一个核心库版本发布（即 [0.2.0-RC3](https://mvnrepository.com/artifact/io.github.talelin/lin-cms-core) ） 
另外需要提示一下：非特殊需求，不建议改写我们内置的 login 和 refresh 接口。一方面后续的版本升级会变得非常麻烦，另一方面也需要改写 AuthorizeVerifyResolver 实现类的检验代码，这都无形增加了自己项目的迭代维护成本。

**Comment by yangxin6** [comment]
好的，明白了，那我就把数据库都改成 int 自增了，感谢
