### ISSUE TITLE
文件上传的Bug

### ISSUE THREAD

**Issue by fuhaodev** [TaleLin/lin-cms-spring-boot#131]
## Bug描述

项目里在预处理器preHandler.handle里做了存库的操作，preHandler.handle的执行先于handleOneFile，而handleOneFile可能处理失败了返回false，但数据库插入成功了，返回给前端数据却是正确的结果（在preHandle里已经提前把数据add了），但是文件并没有真正上传成功，url也是无法访问的。

![截屏2020-11-02 09 20 08](https://user-images.githubusercontent.com/17568641/97821257-ade11100-1cec-11eb-9715-ad76aa62e069.png)

## 如何复现

把secret-key随便改成一个错误的值即可复现。

**Comment by colorful3** [comment]
感谢反馈！我们尽快处理此 bug
