### ISSUE TITLE
七牛云上传图片失败、七牛云的uptoken过期

### ISSUE THREAD

**Issue by HahnLoving** [TaleLin/lin-cms-spring-boot#144]
**描述 bug**

七牛云上传图片失败、七牛云的uptoken过期

**你使用哪个版本出现该问题？**

版本: 0.2.0-RC2

**如何再现**

当项目运行超过一小时以后、七牛云文件上传不了。
我看了一下七牛云当文档、应该是默认的七牛云的token只有1小时、一个小时以后token会过期。
希望可以优化一下代码、当七牛云token过期的生活、重新更新uptoken

**这个是我目前的解决办法**
QiniuUploader.java
`
/**
 /**
     * 处理一个文件数据
     *
     * @param bytes       文件数据，比特流
     * @param newFilename 新文件名称
     * @return 处理是否成功，如果出现异常则返回 false，避免把失败的写入数据库
     */
    @Override
    protected boolean handleOneFile(byte[] bytes, String newFilename) {

        ByteArrayInputStream byteInputStream = new ByteArrayInputStream(bytes);
        try {
            Response response = uploadManager.put(byteInputStream, newFilename, upToken, null, null);
            log.info(response.toString());
            return response.isOK();
        } catch (QiniuException ex) {
            Response r = ex.response;
            log.error("qiniuyun upload file error: {}", r.error);
            return this.refreshHandleOneFile(bytes,newFilename);
        }
    }

    /**
     * 更新uptoken
     *
     * @param bytes       文件数据，比特流
     * @param newFilename 新文件名称
     * @return 处理是否成功，如果出现异常则返回 false，避免把失败的写入数据库
     */
    private boolean refreshHandleOneFile(byte[] bytes, String newFilename){

        Auth auth = Auth.create(accessKey, secretKey);
        upToken = auth.uploadToken(bucket);

        ByteArrayInputStream byteInputStream = new ByteArrayInputStream(bytes);
        try {
            Response response = uploadManager.put(byteInputStream, newFilename, upToken, null, null);
            log.info(response.toString());
            return response.isOK();
        } catch (QiniuException ex) {
            Response r = ex.response;
            log.error("qiniuyun upload file error: {}", r.error);
            return this.refreshHandleOneFile(bytes,newFilename);
        }
    }
`

**Comment by colorful3** [comment]
目前该`bug`已经得到解决，鉴于目前改动较小还没有合并到 master 分支，会再下一个发布的版本修复此`bug`，可参考此
https://github.com/TaleLin/lin-cms-spring-boot/commit/b1e72653004c5b7d32dcb7bbe1238be186ee4037 commit 对源码进行修改。
