### ISSUE TITLE
  @GroupMeta注解已经过时？

### ISSUE THREAD

**Issue by wuzhipeng1991** [TaleLin/lin-cms-spring-boot#150]
如题

**Comment by colorful3** [comment]
是的，直接使用 `@GroupMeta` 注解可以达到 `@GroupRequired` 和 `@PermissionMeta` 合并使用的效果，但从功能上看，两个注解不应耦合到一起，合并注解是一个错误的尝试，容易对使用者造成误解，后面会去掉该注解。
