### ISSUE TITLE
[Log]; API `/cms/log` has not returned the time field

### ISSUE THREAD

**Issue by vanoneang** [TaleLin/lin-cms-spring-boot#165]
**描述 bug**
getLogs 查询所有日志接口，缺少`时间`字段。

AC:
1.  `/cms/log` 返回 time 字段
2. 同步更新[官方文档](https://doc.cms.talelin.com/api/#getlogs-%E6%9F%A5%E8%AF%A2%E6%89%80%E6%9C%89%E6%97%A5%E5%BF%97)

**Comment by colorful3** [comment]
#167 
DONE
