### ISSUE TITLE
用户管理；根据分组 ID 过滤查询返回异常

### ISSUE THREAD

**Issue by vanoneang** [TaleLin/lin-cms-spring-boot#166]
**描述 bug**

API: cms/admin/users?count=2&page=0&group_id=3
Response: 
![image](https://user-images.githubusercontent.com/29253688/105276510-86f3f600-5bdc-11eb-9c60-e8aae6c95a63.png)

**你使用哪个版本出现该问题？**

Domain: face.api.talelin.com

**Comment by colorful3** [comment]
#168
