### ISSUE TITLE
replace-deprecated-api-usage分支分页插件无效，附修改建议

### ISSUE THREAD

**Issue by gadfly3173** [TaleLin/lin-cms-spring-boot#175]
**描述 bug**

branch::`refactor/replace-deprecated-api-usage`分页插件无效

**你使用哪个版本出现该问题？**

branch::`refactor/replace-deprecated-api-usage` commit::`471d212ff33cc30dca82c418adc549544d1a542e`

**修复建议**

由于我自己fork的项目做了大量改动，不方便pr，因此将建议修改的内容写在下面

`lin-cms-spring-boot/src/main/java/io/github/talelin/latticy/common/configuration/CommonConfiguration.java`中line27-30改为

```java
    @Bean
    public MybatisPlusInterceptor mybatisPlusInterceptor() {
        MybatisPlusInterceptor interceptor = new MybatisPlusInterceptor();
        interceptor.addInnerInterceptor(new PaginationInnerInterceptor(DbType.MYSQL));
        return interceptor;
    }
```

**Comment by colorful3** [comment]
谢谢你的修改建议，我们会尽快提交代码。

**Comment by juzi214032** [comment]
感谢反馈
