### ISSUE TITLE
根据文档的操作启动有问题

### ISSUE THREAD

**Issue by nine-city** [TaleLin/lin-cms-spring-boot#207]
拉取git代码
然后更改数据库账号密码
mvn install -Dmaven.test.skip=true之后运行
java -jar target/latticy-0.2.0-RELEASE.jar
就会出现编码为GBK的报错。
![1](https://user-images.githubusercontent.com/20138490/119285841-9449eb80-bc75-11eb-9424-ee3c6cca4025.png)

加上 -Dfile.encoding=utf-8 之后会有新的编码问题
插入数据库是问号乱码
![2](https://user-images.githubusercontent.com/20138490/119285846-97dd7280-bc75-11eb-8961-a87c8ce9e815.png)

![3](https://user-images.githubusercontent.com/20138490/119285835-901dce00-bc75-11eb-976b-ed6de7e7adf8.jpg)

其他Java项目都是正常的。
我在idea里面也设置了编码为UTF8。
文件编码也都是UTF8
数据库是UTF8MB4编码
求救大佬。

**Comment by gadfly3173** [comment]
powershell和cmd也改成utf-8就行。不过如果不在win上部署的话，直接从idea启动就可以了吧

**Comment by nine-city** [comment]
idea直接启动的也是会有编码问题。最后我把Windows系统的编码换成了UTF8才得以解决。
