### ISSUE TITLE
关于配置文件格式

### ISSUE THREAD

**Issue by mini2436** [TaleLin/lin-cms-spring-boot#21]
能否采用utf8作为配置文件的默认格式，虽然不影响使用，但是所有的中文注释全是是乱码看着很难受，要么直接取消注释。

**Comment by fujiale33** [comment]
请问默认不是`utf8`吗？能否截图说明下？

**Comment by mini2436** [comment]
> `utf8`请问而不是吗？能否截图说明下？

<img width="1440" alt="屏幕快照 2020-04-22 上午7 49 40" src="https://user-images.githubusercontent.com/52520081/79925821-ed8d8d00-846d-11ea-92a1-cce4eaa5055b.png">
尝试了vscode所有的编码格式，都无法解决乱码。

**Comment by PedroGao** [comment]
文件确实是 utf8编码的，但是 .properties 文件还是会以 unicode 编码来显示，具体在 idea 中是这样操作的。

![image](https://user-images.githubusercontent.com/23636473/79927461-6b539780-8472-11ea-89d7-0fa0b3899fff.png)
