### ISSUE TITLE
是否能将慕课网的部分的完整sql提供一下?

### ISSUE THREAD

**Issue by alexlee-git** [TaleLin/lin-cms-spring-boot#250]
因为买了慕课网的课程,后端项目是deep-forest 前端是sparrow
但是运行后端项目的sql脚本只有下面这些表
![image](https://user-images.githubusercontent.com/15151031/132450219-757632e0-2142-43a5-a3a8-6fb3765c0cd8.png)
提示有些表找不到
![image](https://user-images.githubusercontent.com/15151031/132450277-c08391bd-9039-4a98-a55a-c48e6a8bed1d.png)
不知道哪里可以得到完整的sql

**Comment by sunlin92** [comment]
去慕课网的git仓库找对应的项目源码
