### ISSUE TITLE
AuthorizeVerifyResolverImpl 的 getClaim 方法存在 bug

### ISSUE THREAD

**Issue by 270686992** [TaleLin/lin-cms-spring-boot#27]
**描述 bug**

- 你是如何操作的？
按文档配置后登录
- 发生了什么？
服务器内部错误
- 你觉得应该出现什么？
登录成功

**你使用哪个版本出现该问题？**
最新版本master分支

如果使用`master`，请表明是 master 分支，否则给出具体的版本号

**如何再现**

If your bug is deterministic, can you give a minimal reproducing code?
Some bugs are not deterministic. Can you describe with precision in which context it happened?
If this is possible, can you share your code?

如果你确定存在这个 bug，你能提供我们一个最小的实现代码吗？
一些 bug 是不确定，只会在某些条件下触发，你能详细描述一下具体的情况和提供复现的步骤吗？
当然如果你提供在线的 repo，那就再好不过了。

bug出现的代码: if (user.getAvatar().startsWith("http")) {...} 出现空指针异常
getAvatar 未判空,if (user.getAvatar() != null && user.getAvatar().startsWith("http")) {...} 修改过后登录成功。

如果你发现了 bug，并修复了它，请用`git rebase`合并成一条标准的`fix: description`提交，然后向我们的
项目提 PR，我们会在第一时间审核，并感谢您的参与。

**Comment by 270686992** [comment]
补充:确认按文档所示开启了auth.enable=true

**Comment by fujiale33** [comment]
谢谢，这个 bug 已经有朋友提 pr 了，马上修复。
