### ISSUE TITLE
关于权限注解,能否提供排序机制

### ISSUE THREAD

**Issue by hejunyuan** [TaleLin/lin-cms-spring-boot#54]
CMS 是一个颇为复杂的应用，它需要的东西太多。我们无法涉及到方方面面，因此关于新特性，我们会以讨论的形式来确定这个特性是否去实现，以什么形式实现。
我们鼓励所有对这个特性感兴趣的人来参与讨论，当然如果你想参与特性的开发那就更好了。

如果你实现了一个 feature，并通过了单元测试，请用`git rebase`合并成一条标准的`feat: description`提交，然后向我们的
项目提 PR，我们会在第一时间审核，并感谢您的参与。

**请问这个特性跟什么问题相关？ 有哪些应用场景？请详细描述。**

比如在权限注解上
@PermissionMeta(value="查询Banner列表")
@PermissionMeta(value="添加Banner")
@PermissionMeta(value="修改Banner")
@PermissionMeta(value="删除Banner")
@PermissionMeta(value="查询单个Banner")

我想让查询单个Banner这个权限放在查询Banner列表后面，能否提供排序机制

**请描述一下你想怎么实现这个特性**

能够在@PermissionMeta上加上order属性 自己设定排序

**讨论**
如果这个特性应用场景非常多，或者非常重要，我们会第一时间去处理。但更多的我们希望更多的人参与讨论，来斟酌它的可行性。

**Comment by PedroGao** [comment]
你的意思是：PermissionMeta 加上一个排序参数，让前端根据这个序号来显示吗？

**Comment by hejunyuan** [comment]
能否在后端取权限集合的时候  就是根据排序参数来排好的

**Comment by PedroGao** [comment]
模块内的按照这个参数排序，那如果模块之间，你觉得需要排序吗？

**Comment by hejunyuan** [comment]
比如 管理员模块  想让它放在最下面或最上面  就调整order的值 最小或者最大  ，比如10000 其余的模块从 9000 8000 7000 开始  里面的增删改查设置成 7001 7002 这样也能满足模块之间的排序。

**Comment by PedroGao** [comment]
我明白你的意思了，这个排序 feature，我们会进行讨论，然后再你恢复。

**Comment by PedroGao** [comment]
前段会在后面增加权限搜索等功能，权限展示的功能还是会交给前段去做。
