### ISSUE TITLE
七牛云文件上传问题

### ISSUE THREAD

**Issue by 270686992** [TaleLin/lin-cms-spring-boot#55]
请详细描述您对本项目的任何问题，我们会在第一时间查阅和解决。
在使用七牛云文件上传的方式时,貌似会生成一个 token 用来文件上传,但是这个 token 是有时间限制的，如果过期了在进行上传会出现上传不到七牛云的而数据库中却有文件记录的情况，希望可以更新一个能够自动在 token 过期后重新获取的机制。
![在这里插入图片描述](http://img-blog.csdnimg.cn/20200525183618676.png)
![在这里插入图片描述](http://img-blog.csdnimg.cn/20200525183852232.png)
![在这里插入图片描述](http://img-blog.csdnimg.cn/20200525183932812.png)

**Comment by 270686992** [comment]
使用的版本为sleeve-0.2.0

**Comment by PedroGao** [comment]
好的，多谢提醒，我们会完善的
