### ISSUE TITLE
配置了七牛 文件上传没进七牛里 数据库type显示local

### ISSUE THREAD

**Issue by ElanYoung** [TaleLin/lin-cms-spring-boot#94]
**描述 bug**
配置了七牛 文件上传没进七牛里 数据库type显示local
- 你是如何操作的？
按照文档配置了七牛 然后直接用postman测试 只改了config.yml文件
- 发生了什么？
![image](https://user-images.githubusercontent.com/39727435/88270245-e80f3f80-cd07-11ea-819b-cda799c8df0a.png)
- 你觉得应该出现什么？
但是七牛查不到 document not found 是不是我少了什么步骤 或者是不止要改配置
**你使用哪个版本出现该问题？**
0.2.0-RC1
如果使用`master`，请表明是 master 分支，否则给出具体的版本号

**如何再现**

If your bug is deterministic, can you give a minimal reproducing code?
Some bugs are not deterministic. Can you describe with precision in which context it happened?
If this is possible, can you share your code?

如果你确定存在这个 bug，你能提供我们一个最小的实现代码吗？
一些 bug 是不确定，只会在某些条件下触发，你能详细描述一下具体的情况和提供复现的步骤吗？
当然如果你提供在线的 repo，那就再好不过了。

如果你发现了 bug，并修复了它，请用`git rebase`合并成一条标准的`fix: description`提交，然后向我们的
项目提 PR，我们会在第一时间审核，并感谢您的参与。

**Comment by juzi214032** [comment]
![image](https://user-images.githubusercontent.com/38206169/89120720-1f8da100-d4eb-11ea-903e-b72349b5517d.png)
请将此处的LocalUploader替换为`QiniuUploader`
