### ISSUE TITLE
"code-message[10022]=未找到相关书籍 "----哈希值怎么转换出来的？

### ISSUE THREAD

**Issue by biotech7** [TaleLin/lin-cms-spring-boot#99]
不错的后端项目。我想问一下，项目中code代码中的提示”未找到相关书籍 “的哈希值通过什么工具转换成了”\u672A\u627E\u5230\u76F8\u5173\u4E66\u7C4D“？再网上找到了一系列哈希转换工具，但是无法转出类似上面的值。我想自定义错误代码提示

**Comment by juzi214032** [comment]
这不是 hash 值，是 unicode 码

**Comment by biotech7** [comment]
非常感谢，已理解！
